version: '3.8'

services:
  backend:
    build:
      context: .
      target: runtime
    volumes:
      # This line maps the 'logs' folder on your host to
      # the '/app/src/logs' directory inside the container,
      # making your log files persistent.
      - ./logs:/app/src/logs
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${BACKEND_PORT}
      API_KEY: ${API_KEY}
      DB_HOST: ${DB_HOST}        
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}        # should still be 3306 inside container
      RATE_LIMIT_WINDOW_MINUTES: ${RATE_LIMIT_WINDOW_MINUTES}
      RATE_LIMIT_MAX: ${RATE_LIMIT_MAX}
    depends_on:
      - db

  backend-test:
    build:
      context: .
      target: test
    environment:
      API_KEY: ${API_KEY}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
    command: ["npm", "test"]

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_HOST_PORT}:3306"
    command: --innodb-buffer-pool-size=64M
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro

volumes:
  db_data:
